TASKS:
#   'top5_abundant_msi_full_rna':
#     input_rna: /lustre/groups/ml01/workspace/anastasia.litinetskaya/code/vitatrack/datasets/V11L12-038_A1.RNA_MOSCOT_paired_hvg.h5ad
#     input_metabolomics: /lustre/groups/ml01/workspace/eirini.giannakoulia/msi_ds/V11L12-038_A1.MSI_MOSCOT_paired_hvg_top5abundant.h5ad
#     split: split
#     methods:
#       ridge:
#         params: params/ridge_params.tsv
#       lasso:
#         params: params/lasso_params.tsv
#       linear:
#         params: params/linreg_params.tsv
#       xgboost:
#         params: params/xgboost_params.tsv
#       elastic_net:
#         params: params/elastic_net_params.tsv
#       cvae:
#         params: params/cvae_params.tsv
#   'top20_abundant_msi_full_rna':
#     input_rna: /lustre/groups/ml01/workspace/anastasia.litinetskaya/code/vitatrack/datasets/V11L12-038_A1.RNA_MOSCOT_paired_hvg.h5ad
#     input_metabolomics: /lustre/groups/ml01/workspace/eirini.giannakoulia/msi_ds/V11L12-038_A1.MSI_MOSCOT_paired_hvg_top20abundant.h5ad
#     split: split
#     methods:
#       ridge:
#         params: params/ridge_params.tsv
#       lasso:
#         params: params/lasso_params.tsv
#       linear:
#         params: params/linreg_params.tsv
#       xgboost:
#         params: params/xgboost_params.tsv
#       elastic_net:
#         params: params/elastic_net_params.tsv
#       cvae:
#         params: params/cvae_params.tsv
#   'top10_abundant_msi_full_rna':
#     input_rna: /lustre/groups/ml01/workspace/anastasia.litinetskaya/code/vitatrack/datasets/V11L12-038_A1.RNA_MOSCOT_paired_hvg.h5ad
#     input_metabolomics: /lustre/groups/ml01/workspace/eirini.giannakoulia/msi_ds/V11L12-038_A1.MSI_MOSCOT_paired_hvg_top10abundant.h5ad
#     split: split
#     methods:
#       ridge:
#         params: params/ridge_params.tsv
#       lasso:
#         params: params/lasso_params.tsv
#       linear:
#         params: params/linreg_params.tsv
#       xgboost:
#         params: params/xgboost_params.tsv
#       elastic_net:
#         params: params/elastic_net_params.tsv
#       cvae:
#         params: params/cvae_params.tsv
  # 'top5_spat_msi_full_rna':
  #   input_rna: /lustre/groups/ml01/workspace/anastasia.litinetskaya/code/vitatrack/datasets/V11L12-038_A1.RNA_MOSCOT_paired_hvg.h5ad
  #   input_metabolomics: /lustre/groups/ml01/workspace/eirini.giannakoulia/msi_ds/V11L12-038_A1.MSI_MOSCOT_paired_hvg_top5spatvar.h5ad
  #   split: split
  #   methods:
  #     ridge:
  #       params: params/ridge_params.tsv
  #     lasso:
  #       params: params/lasso_params.tsv
  #     linear:
  #       params: params/linreg_params.tsv
  #     xgboost:
  #       params: params/xgboost_params.tsv
  #     elastic_net:
  #       params: params/elastic_net_params.tsv
  #     cvae:
  #       params: params/cvae_params.tsv

  'V11L12_MOSCOT_selected_genes_full_msi':
    input_rna: /lustre/groups/ml01/workspace/eirini.giannakoulia/hand_prep/V11L12-038_A1.RNA_MOSCOT_paired_selectedgenesDHB.h5ad
    input_metabolomics: /lustre/groups/ml01/workspace/anastasia.litinetskaya/code/vitatrack/datasets/V11L12-038_B1.MSI_MOSCOT_paired.h5ad
    split: half_split
    methods:
      ridge:
        params: params/ridge_params.tsvz
      lasso:
        params: params/lasso_params.tsv
      linear:
        params: params/linreg_params.tsv
      xgboost:
        params: params/xgboost_params.tsv
      elastic_net:
        params: params/elastic_net_params.tsv
      cvae:
        params: params/cvae_params.tsv

  'V11L12_MOSCOT_selected_genes_selected_msi':
    input_rna: /lustre/groups/ml01/workspace/eirini.giannakoulia/hand_prep/V11L12-038_A1.RNA_MOSCOT_paired_selectedgenesDHB.h5ad
    input_metabolomics: /lustre/groups/ml01/workspace/eirini.giannakoulia/hand_prep/V11L12-038_A1.MSI_MOSCOT_paired_selectedgenesDHB.h5ad
    split: half_split
    methods:
      ridge:
        params: params/ridge_params.tsv
      lasso:
        params: params/lasso_params.tsv
      linear:
        params: params/linreg_params.tsv
      xgboost:
        params: params/xgboost_params.tsv
      elastic_net:
        params: params/elastic_net_params.tsv
      cvae:
        params: params/cvae_params.tsv